/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    /**
     * Button component
     */
    interface ObcButton {
        "fullWidth": boolean;
        "leftAlign": boolean;
        "size": string;
        "variant": string;
    }
    interface ObcIcon {
        /**
          * The icon name
         */
        "iconId": string;
        /**
          * The icon size in pixels
         */
        "sizePx": number;
    }
    interface ObcTooltip {
        "label": string;
        /**
          * Open the tooltip
          * @type {boolean} The tooltip can also be opened by using CSS custom properties: --obc-tooltip-open: 1
         */
        "open": boolean;
        /**
          * Position of the tooltip arrow
          * @type {('above' | 'below' | 'left' | 'right')}
         */
        "position": 'above' | 'below' | 'left' | 'right';
        "text": string;
    }
}
declare global {
    /**
     * Button component
     */
    interface HTMLObcButtonElement extends Components.ObcButton, HTMLStencilElement {
    }
    var HTMLObcButtonElement: {
        prototype: HTMLObcButtonElement;
        new (): HTMLObcButtonElement;
    };
    interface HTMLObcIconElement extends Components.ObcIcon, HTMLStencilElement {
    }
    var HTMLObcIconElement: {
        prototype: HTMLObcIconElement;
        new (): HTMLObcIconElement;
    };
    interface HTMLObcTooltipElement extends Components.ObcTooltip, HTMLStencilElement {
    }
    var HTMLObcTooltipElement: {
        prototype: HTMLObcTooltipElement;
        new (): HTMLObcTooltipElement;
    };
    interface HTMLElementTagNameMap {
        "obc-button": HTMLObcButtonElement;
        "obc-icon": HTMLObcIconElement;
        "obc-tooltip": HTMLObcTooltipElement;
    }
}
declare namespace LocalJSX {
    /**
     * Button component
     */
    interface ObcButton {
        "fullWidth"?: boolean;
        "leftAlign"?: boolean;
        "size"?: string;
        "variant"?: string;
    }
    interface ObcIcon {
        /**
          * The icon name
         */
        "iconId"?: string;
        /**
          * The icon size in pixels
         */
        "sizePx"?: number;
    }
    interface ObcTooltip {
        "label"?: string;
        /**
          * Open the tooltip
          * @type {boolean} The tooltip can also be opened by using CSS custom properties: --obc-tooltip-open: 1
         */
        "open"?: boolean;
        /**
          * Position of the tooltip arrow
          * @type {('above' | 'below' | 'left' | 'right')}
         */
        "position"?: 'above' | 'below' | 'left' | 'right';
        "text"?: string;
    }
    interface IntrinsicElements {
        "obc-button": ObcButton;
        "obc-icon": ObcIcon;
        "obc-tooltip": ObcTooltip;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * Button component
             */
            "obc-button": LocalJSX.ObcButton & JSXBase.HTMLAttributes<HTMLObcButtonElement>;
            "obc-icon": LocalJSX.ObcIcon & JSXBase.HTMLAttributes<HTMLObcIconElement>;
            "obc-tooltip": LocalJSX.ObcTooltip & JSXBase.HTMLAttributes<HTMLObcTooltipElement>;
        }
    }
}
